In [ ]:
# Machine Learning Zoomcamp
# 01-Intro Homework

In [1]:
# Q1

import pandas as pd
pd.__version__

'2.3.2'

In [2]:
df = pd.read_csv('car_fuel_efficiency.csv')

In [3]:
df.describe()

engine_displacement  num_cylinders   horsepower  vehicle_weight  \
count          9704.000000    9222.000000  8996.000000     9704.000000   
mean            199.708368       3.962481   149.657292     3001.280993   
std              49.455319       1.999323    29.879555      497.894860   
min              10.000000       0.000000    37.000000      952.681761   
25%             170.000000       3.000000   130.000000     2666.248985   
50%             200.000000       4.000000   149.000000     2993.226296   
75%             230.000000       5.000000   170.000000     3334.957039   
max             380.000000      13.000000   271.000000     4739.077089   

       acceleration   model_year    num_doors  fuel_efficiency_mpg  
count   8774.000000  9704.000000  9202.000000          9704.000000  
mean      15.021928  2011.484027    -0.006412            14.985243  
std        2.510339     6.659808     1.048162             2.556468  
min        6.000000  2000.000000    -4.000000             6.200971  
25%       13.300000  2006.000000    -1.000000            13.267459  
50%       15.000000  2012.000000     0.000000            15.006037  
75%       16.700000  2017.000000     1.000000            16.707965  
max       24.300000  2023.000000     4.000000            25.967222

In [5]:
# Q2 

number_of_records = len(df)
number_of_records

9704

In [9]:
# Q3

df.head(100)

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                   170            3.0       159.0     3413.433759   
1                   130            5.0        97.0     3149.664934   
2                   170            NaN        78.0     3079.038997   
3                   220            4.0         NaN     2542.392402   
4                   210            1.0       140.0     3460.870990   
..                  ...            ...         ...             ...   
95                  200            2.0       232.0     3476.591797   
96                  120            5.0       172.0     3475.004528   
97                  280            2.0       133.0     3398.340992   
98                  250            NaN       109.0     3210.919484   
99                  240            5.0       194.0     3019.882237   

    acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0           17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1           17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2           15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3           20.2        2009     USA    Diesel    All-wheel drive        2.0   
4           14.4        2009  Europe  Gasoline    All-wheel drive        2.0   
..           ...         ...     ...       ...                ...        ...   
95          11.0        2016     USA  Gasoline    All-wheel drive        1.0   
96          13.8        2013     USA    Diesel    All-wheel drive        NaN   
97          15.3        2015  Europe    Diesel    All-wheel drive        1.0   
98          14.6        2021     USA    Diesel    All-wheel drive        0.0   
99          17.5        2017     USA  Gasoline    All-wheel drive        1.0   

    fuel_efficiency_mpg  
0             13.231729  
1             13.688217  
2             14.246341  
3             16.912736  
4             12.488369  
..                  ...  
95            14.674507  
96            12.743224  
97            13.930128  
98            13.128946  
99            14.882406  

[100 rows x 11 columns]

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9704 entries, 0 to 9703
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   engine_displacement  9704 non-null   int64  
 1   num_cylinders        9222 non-null   float64
 2   horsepower           8996 non-null   float64
 3   vehicle_weight       9704 non-null   float64
 4   acceleration         8774 non-null   float64
 5   model_year           9704 non-null   int64  
 6   origin               9704 non-null   object 
 7   fuel_type            9704 non-null   object 
 8   drivetrain           9704 non-null   object 
 9   num_doors            9202 non-null   float64
 10  fuel_efficiency_mpg  9704 non-null   float64
dtypes: float64(6), int64(2), object(3)
memory usage: 834.1+ KB


In [8]:
df.fuel_type.nunique()

2

In [13]:
# Q4

df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

There are 4 columns with missing values.


In [16]:
#Q5 

df[df['origin']=='Asia']

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                     250            1.0       174.0     2714.219310   
12                    320            5.0       145.0     2783.868974   
14                    200            6.0       160.0     3582.687368   
20                    150            3.0       197.0     2231.808142   
21                    160            4.0       133.0     2659.431451   
...                   ...            ...         ...             ...   
9688                  260            4.0         NaN     3948.404625   
9692                  180            3.0       188.0     3680.341381   
9693                  280            2.0       148.0     2545.070139   
9698                  180            1.0       131.0     3107.427820   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8             10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12            15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14            14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20            18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21             NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   
...            ...         ...    ...       ...                ...        ...   
9688          15.5        2018   Asia    Diesel    All-wheel drive       -1.0   
9692          18.0        2016   Asia  Gasoline  Front-wheel drive        1.0   
9693          15.6        2012   Asia    Diesel    All-wheel drive        0.0   
9698          13.2        2005   Asia  Gasoline  Front-wheel drive       -2.0   
9703          14.7        2005   Asia    Diesel    All-wheel drive       -1.0   

      fuel_efficiency_mpg  
8               16.823554  
12              16.175820  
14              11.871091  
20              18.889083  
21              16.077730  
...                   ...  
9688            11.054830  
9692            11.711653  
9693            17.202782  
9698            13.933716  
9703            14.884467  

[3247 rows x 11 columns]

In [21]:
max_fuel_efficiency_asia = df[df['origin']=='Asia'].fuel_efficiency_mpg.max().round(2)
max_fuel_efficiency_asia

np.float64(23.76)

In [24]:
#Q6 

median_horsepower = df['horsepower'].median()
median_horsepower

np.float64(149.0)

In [25]:
most_frequent_value_horsepower = df['horsepower'].mode()[0]
most_frequent_value_horsepower

np.float64(152.0)

In [27]:
df['horsepower'] = df['horsepower'].fillna(most_frequent_value_horsepower)

In [28]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower               0
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [29]:
median_horsepower = df['horsepower'].median()
median_horsepower

np.float64(152.0)

The median value increased.

In [30]:
#Q7 

len(df)

9704

In [31]:
df_asia = df[df['origin']=='Asia']

In [33]:
df_asia.head(100)

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                    250            1.0       174.0     2714.219310   
12                   320            5.0       145.0     2783.868974   
14                   200            6.0       160.0     3582.687368   
20                   150            3.0       197.0     2231.808142   
21                   160            4.0       133.0     2659.431451   
..                   ...            ...         ...             ...   
307                  140            6.0       128.0     3547.457009   
310                  210            4.0       204.0     3697.288825   
311                  240            2.0       159.0     2916.987921   
312                  210            5.0       152.0     3012.170524   
314                   90            4.0       174.0     3242.774424   

     acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8            10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12           15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14           14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20           18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21            NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   
..            ...         ...    ...       ...                ...        ...   
307          13.7        2021   Asia  Gasoline  Front-wheel drive        1.0   
310          12.8        2017   Asia  Gasoline    All-wheel drive        0.0   
311          16.3        2001   Asia  Gasoline  Front-wheel drive        1.0   
312          15.1        2001   Asia  Gasoline    All-wheel drive        0.0   
314          12.8        2002   Asia    Diesel    All-wheel drive       -1.0   

     fuel_efficiency_mpg  
8              16.823554  
12             16.175820  
14             11.871091  
20             18.889083  
21             16.077730  
..                   ...  
307            12.072259  
310            11.864087  
311            15.066416  
312            16.194433  
314            14.449852  

[100 rows x 11 columns]

In [35]:
len(df_asia)

3247

In [36]:
df_asia_2 = df_asia[['vehicle_weight', 'model_year']]

In [37]:
len(df_asia_2)

3247

In [39]:
df_asia_2.head(100)

vehicle_weight  model_year
8       2714.219310        2016
12      2783.868974        2010
14      3582.687368        2007
20      2231.808142        2011
21      2659.431451        2016
..              ...         ...
307     3547.457009        2021
310     3697.288825        2017
311     2916.987921        2001
312     3012.170524        2001
314     3242.774424        2002

[100 rows x 2 columns]

In [41]:
df_asia_seven_only = df_asia_2.head(7)

In [42]:
len(df_asia_seven_only)

7

In [45]:
df_asia_seven_only.head(10)

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [48]:
X = df_asia_seven_only.values

In [49]:
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [55]:
import numpy as np

In [56]:
XTX = np.dot(X.T, X)

In [58]:
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [57]:
XTX_inverted = np.linalg.inv(XTX)

In [59]:
XTX_inverted

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [60]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [61]:
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [62]:
w = np.dot(np.dot(XTX_inverted, X.T), y)

In [63]:
w

array([0.01386421, 0.5049067 ])

In [64]:
sum_of_all_elements = np.sum(w)

In [66]:
sum_of_all_elements.round(2)

np.float64(0.52)